// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatijaUz.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NatijaUz.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828185745_AddDataProtection")]
    partial class AddDataProtection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.AnswerKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<char>("CorrectAnswer")
                        .HasColumnType("character(1)")
                        .HasColumnName("CORRECT_ANSWER")
                        .HasColumnOrder(3);

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("QUESTION_NUMBER")
                        .HasColumnOrder(2);

                    b.Property<long>("TestId")
                        .HasColumnType("bigint")
                        .HasColumnName("TEST_ID")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("SYS_ANSWER_KEY", "academic");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATE_USER_ID")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(5);

                    b.Property<long>("LearningCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("LEARNING_CENTER_ID")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MODIFIED_AT")
                        .HasColumnOrder(7);

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MODIFIED_USER_ID")
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(1);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SUBJECT")
                        .HasColumnOrder(2);

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("TEACHER_ID")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("LearningCenterId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SYS_GROUP", "academic");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.GroupMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATE_USER_ID")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(3);

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("GROUP_ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MODIFIED_AT")
                        .HasColumnOrder(5);

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MODIFIED_USER_ID")
                        .HasColumnOrder(6);

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("STUDENT_ID")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("SYS_GROUP_MEMBER", "academic");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.LearningCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ADDRESS");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("OWNER_USER_ID");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("PHONE_NUMBER");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("SYS_LEARNING_CENTER", "sys");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("CORRECT_COUNT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IMAGE_URL");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("STATUS");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("STUDENT_ID");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SUBMITTED_AT");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint")
                        .HasColumnName("TEST_ID");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("numeric")
                        .HasColumnName("TOTAL_SCORE");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TestId");

                    b.ToTable("SYS_SUBMISSION", "submission");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.SubmissionAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<char>("DetectedAnswer")
                        .HasColumnType("character(1)")
                        .HasColumnName("DETECTED_ANSWER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_CORRECT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("QUESTION_NUMBER");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SYS_SUBMISSION_ANSWER", "submission");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.Test", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DEADLINE");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("GROUP_ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("QUESTION_COUNT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("SYS_TEST", "academic");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATE_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("FULL_NAME");

                    b.Property<long>("LearningCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("LEARNING_CENTER_ID");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("text")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.HasIndex("LearningCenterId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("SYS_USER", "sys");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.AnswerKey", b =>
                {
                    b.HasOne("NatijaUz.Domain.Entity.Test", "Test")
                        .WithMany("AnswerKeys")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.Group", b =>
                {
                    b.HasOne("NatijaUz.Domain.Entity.LearningCenter", "LearningCenter")
                        .WithMany("Groups")
                        .HasForeignKey("LearningCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatijaUz.Domain.Entity.User", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningCenter");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.GroupMember", b =>
                {
                    b.HasOne("NatijaUz.Domain.Entity.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatijaUz.Domain.Entity.User", "Student")
                        .WithMany("GroupMembers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.Submission", b =>
                {
                    b.HasOne("NatijaUz.Domain.Entity.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("NatijaUz.Domain.Entity.Test", "Test")
                        .WithMany("Submissions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.SubmissionAnswer", b =>
                {
                    b.HasOne("NatijaUz.Domain.Entity.Submission", "Submission")
                        .WithMany("SubmissionAnswers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.Test", b =>
                {
                    b.HasOne("NatijaUz.Domain.Entity.Group", "Group")
                        .WithMany("Tests")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.User", b =>
                {
                    b.HasOne("NatijaUz.Domain.Entity.LearningCenter", "LearningCenter")
                        .WithMany("Users")
                        .HasForeignKey("LearningCenterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LearningCenter");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.Group", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.LearningCenter", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.Submission", b =>
                {
                    b.Navigation("SubmissionAnswers");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.Test", b =>
                {
                    b.Navigation("AnswerKeys");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("NatijaUz.Domain.Entity.User", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("Groups");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
